apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-service
  template:
    metadata:
      labels:
        app: order-service
    spec:
      containers:
        - name: order-service
          image: techdilshan/order-service:latest
          ports:
            - containerPort: 5004
          env:
            - name: PORT
              value: "5004"
          # You can add other environment variables if your service needs them (ex: DB URL, JWT secret, etc.)
